name: Release Process

# このワークフローは、mainブランチへのPRがマージされた時に実行されます
# リリースPRでpackage.jsonのバージョンが更新されている場合、
# 自動的にタグを作成してGitHubリリースを作成します
# 
# 重要: タグプッシュで "Publish to npm" ワークフローをトリガーするために
# RELEASE_PAT (Personal Access Token) をSecretに設定する必要があります

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    # PRがマージされた時のみ実行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得（タグ作成に必要）
          # Personal Access Tokenを使用（他のワークフローをトリガーするため）
          token: ${{ secrets.RELEASE_PAT || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Check for version change
        id: version
        run: |
          # mainブランチとの差分でpackage.jsonのバージョン変更を確認
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:package.json | grep '"version"' | cut -d'"' -f4)
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          if [ "$MAIN_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed from $MAIN_VERSION to $CURRENT_VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=v$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version change detected. Skipping release."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        if: steps.version.outputs.changed == 'true'
        run: |
          git tag ${{ steps.version.outputs.version }}
          echo "Tag ${{ steps.version.outputs.version }} created"
          
      - name: Push tag
        if: steps.version.outputs.changed == 'true'
        run: |
          git push origin --tags

      - name: Create GitHub Release
        if: steps.version.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Changes in this release
            ${{ github.event.pull_request.body }}
            
            ---
            *Released by GitHub Actions*
          draft: false
          prerelease: false